[2025-07-29T22:53:54.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-29T22:53:54.176+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-28T00:00:00+00:00 [queued]>
[2025-07-29T22:53:54.204+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-28T00:00:00+00:00 [queued]>
[2025-07-29T22:53:54.208+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-07-29T22:53:54.264+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-28 00:00:00+00:00
[2025-07-29T22:53:54.307+0000] {standard_task_runner.py:63} INFO - Started process 264 to run task
[2025-07-29T22:53:54.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_etl_dag', 'load_data', 'scheduled__2025-07-28T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_dags.py', '--cfg-path', '/tmp/tmpz58w1gcn']
[2025-07-29T22:53:54.338+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask load_data
[2025-07-29T22:53:54.483+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-29T22:53:54.687+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-28T00:00:00+00:00 [running]> on host 86109165cffe
[2025-07-29T22:53:54.936+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Luis' AIRFLOW_CTX_DAG_ID='pokemon_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-28T00:00:00+00:00'
[2025-07-29T22:53:54.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-29T22:53:55.062+0000] {load.py:39} INFO - Datos de Pokémon leídos exitosamente desde Parquet.
[2025-07-29T22:53:55.065+0000] {load.py:19} INFO - Intentando conectar a la base de datos PostgreSQL...
[2025-07-29T22:53:55.073+0000] {load.py:28} INFO - Error al conectar a la base de datos: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-29T22:53:55.075+0000] {load.py:64} ERROR - Error al cargar los datos de Pokémon en la base de datos: 'NoneType' object has no attribute 'connect'
[2025-07-29T22:53:55.077+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-29T22:53:55.081+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-29T22:53:55.130+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=pokemon_etl_dag, task_id=load_data, execution_date=20250728T000000, start_date=20250729T225354, end_date=20250729T225355
[2025-07-29T22:53:55.273+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-29T22:53:55.334+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-29T22:53:55.340+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
