[2025-08-01T23:28:46.349+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-01T23:28:46.510+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_etl_dag.extract_data scheduled__2025-07-31T00:00:00+00:00 [queued]>
[2025-08-01T23:28:46.540+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_etl_dag.extract_data scheduled__2025-07-31T00:00:00+00:00 [queued]>
[2025-08-01T23:28:46.543+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-08-01T23:28:46.598+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data> on 2025-07-31 00:00:00+00:00
[2025-08-01T23:28:46.677+0000] {standard_task_runner.py:63} INFO - Started process 170 to run task
[2025-08-01T23:28:46.706+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_etl_dag', 'extract_data', 'scheduled__2025-07-31T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_dags.py', '--cfg-path', '/tmp/tmp0vjzfyu2']
[2025-08-01T23:28:46.725+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask extract_data
[2025-08-01T23:28:46.843+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-01T23:28:47.200+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_etl_dag.extract_data scheduled__2025-07-31T00:00:00+00:00 [running]> on host 67c618456cf9
[2025-08-01T23:28:47.762+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Luis' AIRFLOW_CTX_DAG_ID='pokemon_etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-31T00:00:00+00:00'
[2025-08-01T23:28:47.768+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-01T23:28:47.975+0000] {extract.py:92} INFO - Obteniendo lista de generaciones...
[2025-08-01T23:28:48.432+0000] {extract.py:95} INFO - Descargando generation-i desde: https://pokeapi.co/api/v2/generation/1/
[2025-08-01T23:29:03.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-01T23:29:03.536+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pokemon_dags.py", line 53, in extract_data
    asyncio.run(get_raw_species(raw_species_path, api_base_url, generations))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/src/pokemon_etl/extract.py", line 103, in get_raw_species
    with open(raw_path / f"{generation['nombre']}.json", "w", encoding="utf-8") as fout:
              ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'str'
[2025-08-01T23:29:03.728+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=pokemon_etl_dag, task_id=extract_data, execution_date=20250731T000000, start_date=20250801T232846, end_date=20250801T232903
[2025-08-01T23:29:03.780+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task extract_data (unsupported operand type(s) for /: 'str' and 'str'; 170)
[2025-08-01T23:29:03.896+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-01T23:29:03.975+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-01T23:29:03.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
