[2025-07-31T22:57:12.566+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-31T22:57:12.669+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-07-31T22:57:12.693+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-30T00:00:00+00:00 [queued]>
[2025-07-31T22:57:12.696+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-07-31T22:57:12.734+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2025-07-30 00:00:00+00:00
[2025-07-31T22:57:12.764+0000] {standard_task_runner.py:63} INFO - Started process 332 to run task
[2025-07-31T22:57:12.776+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'pokemon_etl_dag', 'load_data', 'scheduled__2025-07-30T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/pokemon_dags.py', '--cfg-path', '/tmp/tmpldqgbooy']
[2025-07-31T22:57:12.786+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask load_data
[2025-07-31T22:57:12.843+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-31T22:57:13.040+0000] {task_command.py:426} INFO - Running <TaskInstance: pokemon_etl_dag.load_data scheduled__2025-07-30T00:00:00+00:00 [running]> on host 79dd1729ef10
[2025-07-31T22:57:13.379+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Luis' AIRFLOW_CTX_DAG_ID='pokemon_etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-30T00:00:00+00:00'
[2025-07-31T22:57:13.385+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-31T22:57:13.581+0000] {load.py:39} INFO - Datos de Pokémon leídos exitosamente desde Parquet.
[2025-07-31T22:57:13.584+0000] {load.py:19} INFO - Intentando conectar a la base de datos PostgreSQL...
[2025-07-31T22:57:21.511+0000] {load.py:28} INFO - Error al conectar a la base de datos: (psycopg2.OperationalError) could not translate host name "pokemon_db" to address: Name or service not known

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-31T22:57:21.513+0000] {load.py:64} ERROR - Error al cargar los datos de Pokémon en la base de datos: 'NoneType' object has no attribute 'connect'
[2025-07-31T22:57:21.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-31T22:57:21.517+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pokemon_dags.py", line 70, in load_data
    load_pokemons_to_db(
  File "/opt/airflow/src/pokemon_etl/load.py", line 60, in load_pokemons_to_db
    with engine.connect() as conn:
         ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'connect'
[2025-07-31T22:57:21.594+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=pokemon_etl_dag, task_id=load_data, execution_date=20250730T000000, start_date=20250731T225712, end_date=20250731T225721
[2025-07-31T22:57:21.637+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task load_data ('NoneType' object has no attribute 'connect'; 332)
[2025-07-31T22:57:21.709+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-31T22:57:21.776+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-31T22:57:21.783+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
